language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: gvQ6qfZcRZRpqdX/lLrn9vWwuc6A4BJjwrcy4ue1gy84UsfZ7yLuLSwqladgGajqRZ2w5o+ByZ4AvMhzcpAK9cCX2rNxIiFkVGNsJY48adUz3RWacV2cSJGbqaczZ2KC6ZrgMKjtA49poKzk3Vc72VUrn1hCf5ulxaawMpNIDWoa0uQoK8RLLVRe29yZl4JyoD59GXlXyW3DX+5oK8WJEHM2zo1AOoCeOJSj0EKEnUXgPS8QZh4RFHNJd+yBUnagC9UAHoE6P4CYhptlvxUAuOnZ6lnZsHVfHtJkBr1JdM8BDDh7gMkdIH0nUIG0A6Pi3HmoZl1Qr6uZAGWH2fIb82tuizN9N7EVYbDuhZtDt4iBVP4NozV743GRo1aqpl3J0AupU8kAU+BphoCJEh+7vLaeqwrm6GgJDW7s39nSGVxEjM5TbUlFgQ2+ltfdDkV0oo4FAwujPA5k+c6rbO+GvRTTJ5D/cfPoOoO1+6RWmjI/Y1nZY1J2N3dmRBu3Fpd+DsLGlJbyzLebgExQwQMWbDg90lHaFdSqUnp/H4McwArBZIJ6KtjtE8mVlSbq1Okb1Gfou0ykCeay++RSfPtlMsz0HvoDRgs8EselQW/cCKPwZivQMPeR7zDNhdvrXiF95oe8On7lXw0uXJbE+VBVex5tzGCeWlJDUoYzH5A40Tk=
  app: kevin-noteful-v2
  on:
    repo: thinkful-ei19/kevin-noteful-v2
services:
- postgresql
before_script:
- psql -U postgres -c 'CREATE DATABASE "noteful-test";'
- psql -U postgres -f ./db/noteful.sql -d noteful-test
