language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: KNvmwhH5SmmxNSOuycHzEZQBzSQ8WHDyqaqDB6CYhz7NXJJm/7al2oBIj7/ZOPPtF6wZNi4AosocrHioS1kKxzlALXtEZMLh49Vl4oyFCY0IsDYI2MuTTrP3K7QjGxX8fhuS12Kh4qLyVBjGFnN1a5MkLDV24gEr68IZumkicOJpXSNuiChrs1L2RORwglqCnTKkJkh/BU2mNxxtsUGWe65Ca9+kMcCzRs1YUjVpufBb0at6J9RtRVcxp04qS0kkwuBcIe4R8l0BLaDsGBTRKDYoPn71RxtGU7JMdDErvhIqfNpFIY3dqQK2fY4AYYshFNfa2IKpZO08nkJ/clDhHlUaBtqUmqk+q2BeBCPOGAF2mje12I5kYrNRrxxfLwnpWqcruv/nv4PuoWWMNsfu3jfGE6WMZeedqO7xx7GW8mvdcsSv8hDiyv7LzJK7EjjMi3eyZpKJvwlHknLyGAQq8hkUz8a4muFYwZ4o7/YcOzbkG6elQl495DG9rjIroKXyDUcQWZ6PHEIPAymeCgt5DFmg043MaaIJU4VvZSfBhlluVCDs6D+roSoVcK0tGwy4GJLkHZ0LcKSUtPzCifQ5MIK1g/TnzpmUVcLzdO3x++ggF8ZRRAyT//0GnchJYnzZEqx+YVom51g7l+0YI+dQEuTvCXscx7nodVQVi/strDM=
  app: desolate-dusk-77065
  on:
    repo: thinkful-ei19/kevin-noteful-v2
services:
- postgresql
before_script:
- psql -U postgres -c 'CREATE DATABASE "noteful-test";'
- psql -U postgres -f ./db/noteful.sql -d noteful-test
